### ISSUE TITLE
Broken on windows

### ISSUE THREAD

**Issue by mg-bayoo** [junnplus/lsp-setup.nvim#31]
Hi, since you moved the module to `nvim-lsp-setup`, the package is broken on windows, because it cannot link to the lsp-setup directory, and the init.lua requires `lsp-setup.utils`

**Comment by soupersauce** [comment]
Don't you have it backwards? cdb09707ae768f97f13ae12c8b7ba9f13c044654
nvim-lsp-setup => lsp-setup.nvim

**Comment by soupersauce** [comment]
Nevermind. I see your point now. Didn't realize the problem was due to a symlink.

**Comment by junnplus** [comment]
@mg-bayoo Sorry for the late reply, I will take the time to fix it soon, PRs are welcome too

**Comment by TisnKu** [comment]
Same here. My current work around is to rename the folder `nvim-lsp-setup` to `lsp-setup` and remove sync link in the installed package.
