### ISSUE TITLE
rust-analyzer not attached to buffer on windows

### ISSUE THREAD

**Issue by TisnKu** [junnplus/lsp-setup.nvim#37]
Hi there, thanks for the plugin. I found the bug that rust lsp cannot load. If I do a fresh reinstall using `:MasonInstall rust-analyzer`, it can be loaded immediately. If I quit nvim and reopen the project, it will not load.

Another workaround is to do a manual setup of rust-analyzer using `require('lsp-config').rust_analyzer.setup()` and remove rust from lsp-setup.nvim.

# Open the main.rs in the project, rust lsp cannot load.
![image](https://user-images.githubusercontent.com/10512841/195001507-f384e57f-8f1e-4739-b8d9-02e6e0a49aa9.png)
![image](https://user-images.githubusercontent.com/10512841/195001518-ed01924d-65c6-4ae2-8c46-b0e8b83baacb.png)
# Reinstall rust-analyzer using mason, lsp can be loaded.
![image](https://user-images.githubusercontent.com/10512841/195001536-7f39259b-64bf-4e84-8a50-7e2127631684.png)

**Comment by TisnKu** [comment]
Seems that using lsp-setup, the `cmd` for rust lsp is not correct.

**Comment by junnplus** [comment]
Can you provide a reproducible minimal configuration?

**Comment by TisnKu** [comment]
Sure. https://github.com/TisnKu/rust-lsp-setup-repro

**Comment by junnplus** [comment]
> If I do a fresh reinstall using :MasonInstall rust-analyzer, it can be loaded immediately. If I quit nvim and reopen the project, it will not load.

It seems that mason doesn't install `rust-analyzer` automatically, or the installation fails.

You need to check if `rust-analyzer` is installed successfully. The following two commands may help you:
- :Mason
- :MasonLog

**Comment by junnplus** [comment]
> Sure. https://github.com/TisnKu/rust-lsp-setup-repro Plugins are in init.lua and lsp configs are in https://github.com/TisnKu/rust-lsp-setup-repro/blob/304929bb9a657e3af4688c5a13d406792429fb6d/after/plugin/lsp.lua.

I am not sure if we need to specify `bundle_path`

**Comment by TisnKu** [comment]
It is installed, just not attached to the buffer. Bundle_path is my random trial to fix the bug, the bug is the same with or without it.
![image](https://user-images.githubusercontent.com/10512841/195052829-84f758dc-6a46-46b7-99e0-361840ac15ac.png)
![image](https://user-images.githubusercontent.com/10512841/195053122-b43fa13d-5f6b-4226-a7bc-5ec3c708ff69.png)

**Comment by junnplus** [comment]
Can you delete the `rust-analyzer` and restart neovim? Then check if mason will automatically install `rust-analyzer`.

**Comment by TisnKu** [comment]
BTW, on my mac, the same configuration works.

**Comment by TisnKu** [comment]
I did some tests for other lsps as well, `taplo` and `rust-analyzer` have the same issue,  `tsserver` and `jsonls` does not.

**Comment by junnplus** [comment]
Sorry, I can't see that this is a problem with lsp-setup, lsp-setup just wraps mason, as you said, it is working on mac.

**Comment by TisnKu** [comment]
If I replace `lsp-setup` with `require('lspconfig').rust_analyzer.setup {}`, it works. Maybe it's a problem of `mason-lspconfig`

**Comment by TisnKu** [comment]
After some testing, I found that with only `mason-lspconfig`, it still works. So I modified the code of lsp-setup just like the example of `mason-lspconfig`, and it works:
![image](https://user-images.githubusercontent.com/10512841/195245909-30ca1844-b562-4505-9b86-5d8a5478b709.png)

It's kind of weird why order matters on windows.

**Comment by TisnKu** [comment]
I opened an issue for `mason-lspconfig` and owner confirmed that `setup` should be placed before `setup_handler`. Do you mind fixing it or accept PR?

**Comment by junnplus** [comment]
> I opened an issue for mason-lspconfig and owner confirmed that setup should be placed before setup_handler. Do you mind fixing it or accept PR?

Thanks, PRs are doubly welcome!
