### ISSUE TITLE
neodev instead of lua-dev

### ISSUE THREAD

**Issue by cppcoffee** [junnplus/lsp-setup.nvim#41]
The config below:

```lua
local settings = {
    servers = {
        sumneko_lua = require('lua-dev').setup(),
    },
}
require('lsp-setup').setup(settings)

```

Then open `.lua` file, prompt message:

`You're using the old way of setting up neodev (previously lua-dev).
Please check the docs at https://github.com/folke/neodev.nvim#-setup`

**Comment by sourabhxyz** [comment]
```lua
-- IMPORTANT: make sure to setup neodev BEFORE lspconfig
require("neodev").setup({
  -- add any options here, or leave empty to use the default settings
})

require('lsp-setup').setup({
  servers = {
    sumneko_lua = {
      settings = {
        Lua = {
          completion = {
            callSnippet = "Replace",
          },
          -- format = {
          --   enable = true,
          -- }
        }
      }
    },
  }
})
```

**Comment by cppcoffee** [comment]
How is it configured in lsp-setup.nvim?

**Comment by sourabhxyz** [comment]
are you asking me @cppcoffee?  I just shared what worked for me. I took the setup from [here](https://github.com/folke/neodev.nvim#-setup).

**Comment by cppcoffee** [comment]
Thank you @sourabhxyz , I using `lsp-setup.nvim` and not sure how the new `neodev` `sumneko_lua` should be configured on lsp-setup.nvim.

If you simply replace `lua-dev` with `neodev`, you get the same prompt, like below:

```lua
local settings = {
    servers = {
        sumneko_lua = require('neodev').setup(),
    },
}
require('lsp-setup').setup(settings)
```

**Comment by sourabhxyz** [comment]
@cppcoffee I am also using `lsp-setup` and [my comment](https://github.com/junnplus/lsp-setup.nvim/issues/41#issuecomment-1288394661) shows how I configured it.

**Comment by cppcoffee** [comment]
Hi @sourabhxyz , using https://github.com/junnplus/lsp-setup.nvim/issues/41#issuecomment-1288394661 , it has been solved.

close issue.
